matrix:
  platform:
    - linux/amd64
  goversion:
    - 1.24

labels:
  platform: ${platform}
    
steps:
  build:
    when:
      event: [push]
    image: golang:${goversion}
    commands:
      - apt-get update
      - apt-get install -y libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
      - go get
      - go build

  linter:
    when:
      event: [push]
    image: golang:${goversion}
    commands:
      - apt-get update
      - apt-get install -y libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.5.0
      - golangci-lint --version
      - golangci-lint run ./...
    depends_on: [build]
